# Impacket - Collection of Python classes for working with network protocols.
#
# Copyright Fortra, LLC and its affiliated companies
#
# All rights reserved.
#
# This software is provided under a slightly modified version
# of the Apache Software License. See the accompanying LICENSE file
# for more information.
#
# Full transparency, this was generated by AI and edited by myself as neccesary/needed
# Tested so far:
#   ICatalogSession       InitializeSession, GetServerInformation
#   ICatalog64BitSupport  SupportsMultipleBitness, Initialize64BitQueryCellSupport
#   ICatalogTableInfo     GetClientTableInfo
#   ICatalogTableRead     ReadTable
#   ICapabilitySupport    IsInstalled, IsRunning
#   IContainerControl2    GetRunningContainers
#
from __future__ import division
from __future__ import print_function

import pytest
import unittest
from tests import RemoteTestCase
from tests.dcerpc import DCERPCTests

from impacket import ntlm
from impacket.dcerpc.v5 import dcomrt
from impacket.dcerpc.v5.dcom import coma


class COMATests(DCERPCTests):

    string_binding = r"ncacn_ip_tcp:{0.machine}"
    authn = True
    authn_level = ntlm.NTLM_AUTH_PKT_INTEGRITY

    def test_ICatalogSession(self):
        dce, rpctransport = self.connect()
        scm = dcomrt.IRemoteSCMActivator(dce)
        iInterface = scm.RemoteCreateInstance(coma.CLSID_COMAServer, coma.IID_ICatalogSession)
        iCatalogSession = coma.ICatalogSession(iInterface)
        iCatalogSession.InitializeSession(0.0, 100.0, 0)
        iCatalogSession.GetServerInformation()

    def test_ICatalog64BitSupport(self):
        dce, rpctransport = self.connect()
        scm = dcomrt.IRemoteSCMActivator(dce)
        iInterface = scm.RemoteCreateInstance(coma.CLSID_COMAServer, coma.IID_ICatalogSession)
        iCatalogSession = coma.ICatalogSession(iInterface)
        iCatalogSession.InitializeSession(0.0, 100.0, 0)
        iInterface = iCatalogSession.RemQueryInterface(1, (coma.IID_ICatalog64BitSupport,))
        iCatalog64BitSupport = coma.ICatalog64BitSupport(iInterface)
        iCatalog64BitSupport.SupportsMultipleBitness()
        iCatalog64BitSupport.Initialize64BitQueryCellSupport(1)

    @pytest.mark.skip
    def test_ICatalogTableRead(self):
        dce, rpctransport = self.connect()
        scm = dcomrt.IRemoteSCMActivator(dce)
        iInterface = scm.RemoteCreateInstance(coma.CLSID_COMAServer, coma.IID_ICatalogSession)
        iCatalogSession = coma.ICatalogSession(iInterface)
        iCatalogSession.InitializeSession(0.0, 100.0, 0)
        iInterface = iCatalogSession.RemQueryInterface(1, (coma.IID_ICatalogTableInfo,))
        iCatalogTableInfo = coma.ICatalogTableInfo(iInterface)
        iCatalogTableRead = iCatalogTableInfo.GetClientTableInfo(coma.CATID_COMA, coma.TBLID_Conglomerations)
        iCatalogTableRead.ReadTable(coma.CATID_COMA, coma.TBLID_Conglomerations)

    @pytest.mark.skip
    def test_ICapabilitySupport(self):
        dce, rpctransport = self.connect()
        scm = dcomrt.IRemoteSCMActivator(dce)
        iInterface = scm.RemoteCreateInstance(coma.CLSID_COMAServer, coma.IID_ICatalogSession)
        iCatalogSession = coma.ICatalogSession(iInterface)
        iCatalogSession.InitializeSession(0.0, 100.0, 0)
        iInterface = iCatalogSession.RemQueryInterface(1, (coma.IID_ICapabilitySupport,))
        iCapabilitySupport = coma.ICapabilitySupport(iInterface)
        iCapabilitySupport.IsInstalled(coma.CatSrvServices.css_lb)
        iCapabilitySupport.IsRunning(coma.CatSrvServices.css_lb)

    @pytest.mark.skip
    def test_IContainerControl2(self):
        dce, rpctransport = self.connect()
        scm = dcomrt.IRemoteSCMActivator(dce)
        iInterface = scm.RemoteCreateInstance(coma.CLSID_COMAServer, coma.IID_ICatalogSession)
        iCatalogSession = coma.ICatalogSession(iInterface)
        iCatalogSession.InitializeSession(0.0, 100.0, 0)
        iInterface = iCatalogSession.RemQueryInterface(1, (coma.IID_IContainerControl2,))
        iContainerControl2 = coma.IContainerControl2(iInterface)
        iContainerControl2.GetRunningContainers(coma.GUID_DefaultAppPartition, coma.GUID_ProtectedConglomeration_SystemApplication)


@pytest.mark.remote
class COMAConnectionTests(RemoteTestCase, unittest.TestCase):

    def setUp(self):
        self.set_transport_config()

    def test_RemQueryInterface(self):
        dcom = dcomrt.DCOMConnection(self.machine, self.username, self.password, self.domain, self.lmhash, self.nthash)
        iInterface = dcom.CoCreateInstanceEx(coma.CLSID_COMAServer, coma.IID_ICatalogSession)
        iCatalogSession = coma.ICatalogSession(iInterface)
        iCatalogSession.RemQueryInterface(1, (coma.IID_ICatalogSession,))
        dcom.disconnect()

    def test_RemRelease(self):
        dcom = dcomrt.DCOMConnection(self.machine, self.username, self.password, self.domain, self.lmhash, self.nthash)
        iInterface = dcom.CoCreateInstanceEx(coma.CLSID_COMAServer, coma.IID_ICatalogSession)
        iCatalogSession = coma.ICatalogSession(iInterface)
        iCatalogSession.RemRelease()
        dcom.disconnect()

    @pytest.mark.remote
    def test_coma(self):
        dcom = dcomrt.DCOMConnection(self.machine, self.username, self.password, self.domain, self.lmhash, self.nthash)
        iInterface = dcom.CoCreateInstanceEx(coma.CLSID_COMAServer, coma.IID_ICatalogSession)

        iCatalogSession = coma.ICatalogSession(iInterface)
        iCatalogSession.InitializeSession(0.0, 100.0, 0)
        iCatalogSession.GetServerInformation()

        iInterface = iCatalogSession.RemQueryInterface(1, (coma.IID_ICatalog64BitSupport,))
        iCatalog64BitSupport = coma.ICatalog64BitSupport(iInterface)
        iCatalog64BitSupport.SupportsMultipleBitness()

        iInterface = iCatalogSession.RemQueryInterface(1, (coma.IID_ICatalogTableInfo,))
        iCatalogTableInfo = coma.ICatalogTableInfo(iInterface)
        iCatalogTableRead = iCatalogTableInfo.GetClientTableInfo(coma.CATID_COMA, coma.TBLID_Conglomerations)
        iCatalogTableRead.ReadTable(coma.CATID_COMA, coma.TBLID_Conglomerations)

        #iInterface = iCatalogSession.RemQueryInterface(1, (coma.IID_IContainerControl2,))
        #iContainerControl2 = coma.IContainerControl2(iInterface)
        #iContainerControl2.GetRunningContainers(coma.GUID_DefaultAppPartition, coma.GUID_ProtectedConglomeration_SystemApplication)

        iCatalogSession.RemRelease()
        dcom.disconnect()


@pytest.mark.remote
class COMATestsTCPTransport(COMATests, unittest.TestCase):
    transfer_syntax = DCERPCTests.TRANSFER_SYNTAX_NDR


@pytest.mark.remote
class COMATestsTCPTransport64(COMATests, unittest.TestCase):
    transfer_syntax = DCERPCTests.TRANSFER_SYNTAX_NDR64


# Process command-line arguments.
if __name__ == "__main__":
    unittest.main(verbosity=1)
